# Abuse words list - Hindi/Urdu slangs
abuse_words = {
    "kaadmi",
    "ghantachor", 
    "tharkipan",
    "maalchusak",
    "jhaanduba",
    "madarchod",
    "behenchod", 
    "chutiya",
    "gaand",
    "bhosdike",
    "lund",
    "chod",
    "chut",
    "randi",
    "kutta", 
    "kutti",
    "bhenchod",
    "mc",
    "bc"
}

# Add all the additional words you provided
abuse_words.update({
    "kaamchor",
    "ghatia",
    "lauda",
    "randichor",
    "chodchor",
    "jhantuchor",
    "chootfaad",
    "gaandmara",
    "lodu",
    "gandchus",
    "jhatupeet",
    "jhattichor",
    "chammakchallo",
    "chiknichoot",
    "chodmachine",
    "rakhailbaaz",
    "kuttafaad",
    "bhosadi",
    "tinduchor",
    "tattichor",
    "khoot",
    "rakhwala",
    "nibbanibbi",
    "bhaluchor",
    "kuttey",
    "bhonsdike",
    "maawe",
    "choddey",
    "laudebaaz",
    "chodpan",
    "laudey",
    "tattiwaala",
    "chiknichod",
    "gandphaad",
    "phattuchor",
    "lundwa",
    "chodpakad",
    "chootbaj",
    "lundchodan",
    "muthmar",
    "tharkiitem",
    "mutkhor",
    "charsi",
    "tharkiyapan",
    "gaandgiri",
    "kamchor",
    "kaminegi",
    "chodgiri",
    "pichwafad",
    "muthkhor",
    "jhantuwaala",
    "gandghusa",
    "hijda",
    "chakka",
    "kinnar",
    "chodwan",
    "jhaatpoka",
    "chodkar",
    "rudiya",
    "bhojpuriya",
    "lutwa",
    "lodi",
    "ganjapan",
    "nalayakon",
    "kamineon",
    "rakkhas",
    "lundgiri",
    "faadmaar",
    "gandkhol",
    "chutmaar",
    "jhantichaat",
    "chootkhol",
    "lundghusa",
    "maalchod",
    "chodpanti",
    "jhattimar",
    "bhosachod",
    "phuddiya",
    "phuddifaad",
    "chootpeet",
    "kharapcheez",
    "jhaatan",
    "chootu",
    "gandbazaar",
    "tandooribhoot",
    "maallover",
    "pudina",
    "laudepeet",
    "jhatujhat",
    "nibbigiri",
    "chodma",
    "ghanta",
    "maachod",
    "chirkutya",
    "jhaant",
    "ghassu",
    "lundbaaz",
    "chodu",
    "bhadve",
    "jhatu",
    "kameeni",
    "haraamzadi",
    "bhojpuri",
    "randibaaz",
    "gaandfat",
    "gaandfattu",
    "madharchod",
    "kutri",
    "chintu",
    "tatti",
    "mutra",
    "jhantuwa",
    "lundmar",
    "chirkutpan",
    "muth",
    "chootmaar",
    "bhadwagiri",
    "taporiya",
    "kaminepan",
    "mufaad",
    "tind",
    "chootbaaz",
    "chodna",
    "mamechod",
    "pichwada",
    "lundchod",
    "pottywaala",
    "bhosda",
    "tharak",
    "ganduchor",
    "beghairat",
    "ghatiyapan",
    "randipan",
    "ghapla",
    "chudai",
    "chodibaaz",
    "maalbaaz",
    "tharkiwaala",
    "gaandchatu",
    "nalayaki",
    "bahanchod",
    "suarwaala",
    "chootkhor",
    "lulli",
    "bhosdapan",
    "chutpan",
    "jhaatbaaz",
    "kuchchod",
    "badtameez",
    "khotta",
    "gandbaz",
    "chikne",
    "nibbi",
    "nibba",
    "faltupan",
    "ulluwaala",
    "suarpan",
    "chudakkar",
    "tharakpan",
    "bhediya",
    "janani",
    "badbakht",
    "lutera",
    "haramgiri",
    "sharampan",
    "nanga",
    "bhagwanchod",
    "nalla",
    "maalfaad",
    "chootdho",
    "phuddi",
    "chootlut",
    "baapchod",
    "maachuda",
    "bhosdikay",
    "jhatmar",
    "laude",
    "laudapan",
    "randiya",
    "chutme",
    "chodde",
    "madar",
    "motherchod",
    "randiwaala",
    "jhaatwala",
    "lundiyabaaz"
})

# You can add more words or load from external file
def load_additional_words(file_path):
    """Load additional abuse words from file"""
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            additional_words = set(line.strip().lower() for line in f if line.strip())
            abuse_words.update(additional_words)
            return True
    except FileNotFoundError:
        return False

def get_abuse_words():
    """Return the current set of abuse words"""
    return abuse_words.copy()

def add_abuse_word(word):
    """Add a new word to the abuse list"""
    abuse_words.add(word.lower())
    return True

def remove_abuse_word(word):
    """Remove a word from the abuse list"""
    if word.lower() in abuse_words:
        abuse_words.remove(word.lower())
        return True
    return False

def get_word_count():
    """Return the number of abuse words in the list"""
    return len(abuse_words)